### ISSUE TITLE
Client use of roots.pem?

### ISSUE THREAD

**Issue by unludo** [salrashid123/gcegrpc#3]
Hello,
In your examples, the client uses server_crt.pem to communicate with the server.
Is it possible to have the client use the roots.pem, or CA_crt.pem in this repo instead of the server_crt.pem?
More like it works in https, with only the root cert, and the chain of certs?
The reason is that if the cert is updated for security reason, the client does not need to be updated.
Actually I tried but it fails with a message like this:

```
E0612 16:11:33.693316575    8159 ssl_transport_security.cc:1238] Handshake failed 
with fatal error SSL_ERROR_SSL: error:14090086:SSL
routines:ssl3_get_server_certificate:certificate verify failed
```

Thanks

**Comment by salrashid123** [comment]
you'll need to set the `serverName` field and CA inside a [tls.Config](https://godoc.org/crypto/tls#Config) and startup the client credentials.

ill update the sample w/ ths info instead of the direct servername 

- https://github.com/salrashid123/gcegrpc/blob/master/app/grpc_backend/src/grpc_client.go#L29

```golang
	//ce, err := credentials.NewClientTLSFromFile("server_crt.pem", "")

	var tlsCfg tls.Config
	rootCAs := x509.NewCertPool()
	pem, err := ioutil.ReadFile("CA_crt.pem")
	if err != nil {
		log.Fatalf("failed to load root CA certificates  error=%v", err)
	}
	if !rootCAs.AppendCertsFromPEM(pem) {
		log.Fatalf("no root CA certs parsed from file ")
	}
	tlsCfg.RootCAs = rootCAs
	tlsCfg.ServerName = "server.domain.com"

	ce := credentials.NewTLS(&tlsCfg)
````

**Comment by salrashid123** [comment]
fixed in  https://github.com/salrashid123/gcegrpc/commit/04df2708b6e02294757f90ffe1899654d6dd3279

**Comment by unludo** [comment]
Hello @salrashid123,

Related to this issue, I tried to make the solution work with letsencrypt in GKE. The issue is that there is no intermediate certificate, and the root cert does not work.
Would you have an idea on how to make it work with letsencrypt?

Thanks

**Comment by salrashid123** [comment]
if you're using GKE managed certs (letsencrypt), you shoulnt' have to specify the root certs (lets encrypte signed certs are valid).  if you've deployed a gke service and have a `CN=mygrpcserver.domain.com`  just dial the connection using that name directly; no need to setup intermediate certs

**Comment by Nabulio** [comment]
Hi @salrashid123 
Thank you for your great work. Sorry, I know this issue is closed. But I have a question related to this configuration:

      

      containers:        
      - name: hc-proxy
        
        image: docker.io/salrashid123/grpc_health_proxy:1.0.0
        
        args: [
          "--http-listen-addr=0.0.0.0:8080",
          "--grpcaddr=localhost:50051",
          "--service-name=echo.EchoServer",
          "--https-listen-ca=/config/CA_crt_hc.pem",
          "--https-listen-cert=/certs/http_server_crt.pem",
          "--https-listen-key=/certs/http_server_key.pem",
          "--grpctls",        
          "--grpc-sni-server-name=server.domain.com",
          "--grpc-ca-cert=/config/CA_crt_grpc_server.pem",
          "--logtostderr=1",
          "-v=1"
        ]

If I already have a self managed certs (tls.key and tls.crt) for a comodin domain (i.e *.mydomain.io). How would be set the config in the previous snippet? Do I just have to setup the .key and .crt certs?

Thanks for your help.
